name: pier
version: 0.3.0.0
license: BSD3
maintainer: judah.jacobson@gmail.com
synopsis: Yet another Haskell build system.
description: |
    Pier is a command-line tool for building Haskell projects.  It is
    similar in purpose to <https://www.haskellstack.org Stack>,
    but explores a different design:

    * Pier implements the fine-grained Haskell build logic from (nearly)
      scratch.  In contrast, Stack relies on Cabal to implement most of its
      build steps, giving it a more coarse control over the build.
    * Pier uses general-purpose libraries for implementing build systems, namely
      <https://shakebuild.com Shake> and <https://hackage.haskell.org/package/pier-core pier-core>.

    For more information, see the official <https://github.com/judah/pier/blob/master/Readme.md documentation>.

category: Development
github: judah/pier

# Work around haskell/cabal#4739
when:
  - condition: os(darwin)
    ghc-options: -optP-Wno-nonportable-include-path

executables:
  pier:
    source-dirs: 'src'
    main: Main.hs
    ghc-options: -threaded -with-rtsopts=-I0
    dependencies:
      - Cabal == 2.2.*
      - aeson >= 1.3 && < 1.5
      - base == 4.11.*
      - binary == 0.8.*
      - binary-orphans == 0.1.*
      - containers == 0.5.*
      - directory >= 1.3.1 && < 1.4
      - hashable == 1.2.*
      - optparse-applicative
      - pier-core == 0.3.*
      - shake == 0.16.*
      - split == 0.2.*
      - text == 1.2.*
      - transformers == 0.5.*
      - unordered-containers == 0.2.*
      - yaml >= 0.8 && < 0.11
    default-extensions: !include "../common-extensions.yaml"
